/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long int
#endif

int cost_function_derivative_combined(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void cost_function_derivative_combined_incref(void);
void cost_function_derivative_combined_decref(void);
casadi_int cost_function_derivative_combined_n_out(void);
casadi_int cost_function_derivative_combined_n_in(void);
const char* cost_function_derivative_combined_name_in(casadi_int i);
const char* cost_function_derivative_combined_name_out(casadi_int i);
const casadi_int* cost_function_derivative_combined_sparsity_in(casadi_int i);
const casadi_int* cost_function_derivative_combined_sparsity_out(casadi_int i);
int cost_function_derivative_combined_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
