/* 
 * This file was automatically generated by CasADi.
 * The CasADi copyright holders make no ownership claim of its contents. 
 * x = MX.sym('x ',2) 
 * y = MX.sym('y') 
 * f = Function('f',[x ,y],[x,sin(y)*x],['x','y'],['r','q'])
 * f.generate('gen.c')
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) gen_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

void CASADI_PREFIX(copy)(const real_t* x, int n, real_t* y) {
  int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}
#define copy(x, n, y) CASADI_PREFIX(copy)(x, n, y)

static const int CASADI_PREFIX(s0)[6] = {2, 1, 0, 2, 0, 1};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[5] = {1, 1, 0, 1, 0};
#define s1 CASADI_PREFIX(s1)
/* f 
 * x = MX.sym('x ',2) 
 * y = MX.sym('y') 
 * f = Function('f',[x ,y],[x,sin(y)*x],['x','y'],['r','q'])
 * f.generate('gen.c')
 * 
 * parameters:
 *  arg = input
 *  * arg[0]=x -> real vector(2 elements)
 *  * arg[1]=y -> real number
 *  res = output
 *  * arg[0]=x -> real vector(2 elements)
 *  * arg[1]=y -> real vector(2 elements)
 * iw???? not used
 * w -> buffer , used in between to store processed versions of x
 * mem???? not used
 */
int f(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  const real_t *cs;
  int i;
  real_t *rr;
  real_t *w0=w+0, w1;
  /* #0: Input 0 (x), part 0 (x ) */
  copy(arg[0], 2, w0);
  /* #1: Output 0 (r) */
  copy(w0, 2, res[0]);
  /* #2: Input 1 (y), part 0 (y) */
  w1 = arg[1] ? arg[1][0] : 0;
  /* #3: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #4: @0 = (@1*@0) */
  for (i=0, rr=w0, cs=w0; i<2; ++i) (*rr++)  = (w1*(*cs++));
  /* #5: Output 1 (q) */
  copy(w0, 2, res[1]);
  return 0;
}

void f_incref(void) {
}

void f_decref(void) {
}

int f_n_in(void) { return 2;}

int f_n_out(void) { return 2;}

const char* f_name_in(int i){
  switch (i) {
    case 0: return "x";
    case 1: return "y";
    default: return 0;
  }
}

const char* f_name_out(int i){
  switch (i) {
    case 0: return "r";
    case 1: return "q";
    default: return 0;
  }
}

const int* f_sparsity_in(int i) {
  switch (i) {
    case 0: return s0;
    case 1: return s1;
    default: return 0;
  }
}

const int* f_sparsity_out(int i) {
  switch (i) {
    case 0: return s0;
    case 1: return s0;
    default: return 0;
  }
}

int f_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 3;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
